import { defineType, defineField } from "sanity";

export default defineType({
  name: "post",
  title: "Post",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Title", type: "string", validation: (r) => r.required() }),
    defineField({ name: "titleLoc", title: "Title (localized)", type: "localeString" }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "title" }, validation: (r) => r.required() }),
    defineField({ name: "excerpt", title: "Excerpt", type: "text" }),
    defineField({ name: "excerptLoc", title: "Excerpt (localized)", type: "localeText" }),
    defineField({ name: "body", title: "Body", type: "array", of: [{ type: "block" }] }),
    defineField({ name: "bodyLoc", title: "Body (localized)", type: "localeBlock" }),
    defineField({ name: "mainImage", title: "Main image", type: "image", options: { hotspot: true } }),
    defineField({ name: "videoUrl", title: "Video URL (optional)", type: "url" }),
    defineField({ name: "videoPoster", title: "Video Poster (optional)", type: "image", options: { hotspot: true } }),
    // Taxonomy
    defineField({ name: "category", title: "Category (single)", type: "string", options: { list: [
      { title: "Photography", value: "photography" },
      { title: "Video", value: "video" },
      { title: "Video Editing", value: "video-editing" },
      { title: "Tours 360", value: "tours360" },
      { title: "Plans / 3D", value: "plans3d" },
      { title: "Aerial/Drone", value: "aerial-drone" },
      { title: "Google Street View", value: "google-street-view" },
      { title: "Scans / Fotogrametria", value: "scans-fotogrametria" },
      { title: "Virtual Staging", value: "virtual-staging" },
      { title: "Social Media Content", value: "social-media" },
      { title: "Landing Pages", value: "landing-pages" },
      { title: "Campanas de Marketing", value: "marketing-campaigns" },
      { title: "Carteleria Inmobiliaria", value: "carteleria-inmobiliaria" },
      { title: "Visitas Interactivas Unreal", value: "unreal-interactive" },
      { title: "Inteligencia Artificial", value: "inteligencia-artificial" },
      { title: "Vendedores IA", value: "vendedores-ia" },
      { title: "Automation / AI", value: "automation" },
    ] } }),
    defineField({ name: "categories", title: "Categories (multi)", type: "array", of: [{ type: "string" }], options: { list: [
      { title: "Photography", value: "photography" },
      { title: "Video", value: "video" },
      { title: "Video Editing", value: "video-editing" },
      { title: "Tours 360", value: "tours360" },
      { title: "Plans / 3D", value: "plans3d" },
      { title: "Aerial/Drone", value: "aerial-drone" },
      { title: "Google Street View", value: "google-street-view" },
      { title: "Scans / Fotogrametria", value: "scans-fotogrametria" },
      { title: "Virtual Staging", value: "virtual-staging" },
      { title: "Social Media Content", value: "social-media" },
      { title: "Landing Pages", value: "landing-pages" },
      { title: "Campanas de Marketing", value: "marketing-campaigns" },
      { title: "Carteleria Inmobiliaria", value: "carteleria-inmobiliaria" },
      { title: "Visitas Interactivas Unreal", value: "unreal-interactive" },
      { title: "Inteligencia Artificial", value: "inteligencia-artificial" },
      { title: "Vendedores IA", value: "vendedores-ia" },
      { title: "Automation / AI", value: "automation" },
    ] } }),
    // Editorial tags
    defineField({ name: "industryTags", title: "Industry Tags", type: "array", of: [{ type: "string" }], options: { list: [
      { title: "Real Estate", value: "real-estate" },
      { title: "Hospitality", value: "hospitality" },
      { title: "Retail", value: "retail" },
      { title: "Education", value: "education" },
      { title: "Tourism", value: "tourism" },
      { title: "Industrial", value: "industrial" },
    ] } }),
    defineField({ name: "objectiveTags", title: "Objective Tags", type: "array", of: [{ type: "string" }], options: { list: [
      { title: "Lead Gen", value: "lead-gen" },
      { title: "Branding", value: "branding" },
      { title: "Ventas", value: "ventas" },
      { title: "Documentacion", value: "documentacion" },
    ] } }),
    defineField({ name: "formatTags", title: "Format Tags", type: "array", of: [{ type: "string" }], options: { list: [
      { title: "4K", value: "4k" },
      { title: "8K", value: "8k" },
      { title: "Vertical", value: "vertical" },
      { title: "HDR", value: "hdr" },
      { title: "360°", value: "360" },
    ] } }),
    defineField({ name: "platformTags", title: "Platform Tags", type: "array", of: [{ type: "string" }], options: { list: [
      { title: "Web", value: "web" },
      { title: "Instagram", value: "instagram" },
      { title: "YouTube", value: "youtube" },
      { title: "Google Maps", value: "google-maps" },
    ] } }),
    defineField({ name: "publishedAt", title: "Published at", type: "datetime", initialValue: () => new Date().toISOString() }),

    // SEO per item
    defineField({ name: "seoTitleLoc", title: "SEO Title (localized)", type: "localeSeoTitle" }),
    defineField({ name: "seoDescriptionLoc", title: "SEO Description (localized)", type: "localeSeoDescription" }),
    defineField({ name: "ogImage", title: "OG Image (optional)", type: "image", options: { hotspot: true } }),
    defineField({ name: "autoSyncSeo", title: "Auto-sync translations if not manually edited", type: "boolean", initialValue: true }),
  ],
  preview: {
    select: { title: "title", media: "mainImage" },
  },
});
