import { defineType, defineField } from "sanity";

export default defineType({
  name: "project",
  title: "Project",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Title", type: "string", validation: (r) => r.required() }),
    defineField({ name: "titleLoc", title: "Title (localized)", type: "localeString" }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "title" } }),
    defineField({ name: "thumb", title: "Thumbnail", type: "image", options: { hotspot: true } }),
    defineField({ name: "videoUrl", title: "Video URL (Bunny/YouTube/Vimeo/MP4)", type: "url", description: "If set, detail page will show this video instead of the thumbnail." }),
    defineField({ name: "videoPoster", title: "Video Poster (optional)", type: "image", options: { hotspot: true } }),
    defineField({ name: "tourUrl", title: "Virtual Tour URL (3D Vista or iframe URL)", type: "url", description: "If set, the detail page will show this tour embed above the body." }),
    defineField({ name: "tags", title: "Tags", type: "array", of: [{ type: "string" }] }),
    // Taxonomy
    defineField({ name: "category", title: "Category (single)", type: "string", options: { list: [
      { title: "Photography", value: "photography" },
      { title: "Video", value: "video" },
      { title: "Video Editing", value: "video-editing" },
      { title: "Tours 360", value: "tours360" },
      { title: "Plans / 3D", value: "plans3d" },
      { title: "Aerial/Drone", value: "aerial-drone" },
      { title: "Google Street View", value: "google-street-view" },
      { title: "Scans / Fotogrametria", value: "scans-fotogrametria" },
      { title: "Virtual Staging", value: "virtual-staging" },
      { title: "Social Media Content", value: "social-media" },
      { title: "Landing Pages", value: "landing-pages" },
      { title: "Campanas de Marketing", value: "marketing-campaigns" },
      { title: "Carteleria Inmobiliaria", value: "carteleria-inmobiliaria" },
      { title: "Visitas Interactivas Unreal", value: "unreal-interactive" },
      { title: "Inteligencia Artificial", value: "inteligencia-artificial" },
      { title: "Vendedores IA", value: "vendedores-ia" },
      { title: "Automation / AI", value: "automation" },
    ] } }),
    defineField({ name: "categories", title: "Categories (multi)", type: "array", of: [{ type: "string" }], options: { list: [
      { title: "Photography", value: "photography" },
      { title: "Video", value: "video" },
      { title: "Video Editing", value: "video-editing" },
      { title: "Tours 360", value: "tours360" },
      { title: "Plans / 3D", value: "plans3d" },
      { title: "Aerial/Drone", value: "aerial-drone" },
      { title: "Google Street View", value: "google-street-view" },
      { title: "Scans / Fotogrametria", value: "scans-fotogrametria" },
      { title: "Virtual Staging", value: "virtual-staging" },
      { title: "Social Media Content", value: "social-media" },
      { title: "Landing Pages", value: "landing-pages" },
      { title: "Campanas de Marketing", value: "marketing-campaigns" },
      { title: "Carteleria Inmobiliaria", value: "carteleria-inmobiliaria" },
      { title: "Visitas Interactivas Unreal", value: "unreal-interactive" },
      { title: "Inteligencia Artificial", value: "inteligencia-artificial" },
      { title: "Vendedores IA", value: "vendedores-ia" },
      { title: "Automation / AI", value: "automation" },
    ] } }),
    defineField({ name: "gallery", title: "Gallery", type: "array", of: [{ type: "image", options: { hotspot: true } }] }),
    defineField({ name: "body", title: "Body", type: "array", of: [{ type: "block" }] }),
    defineField({ name: "bodyLoc", title: "Body (localized)", type: "localeBlock" }),
    defineField({ name: "date", title: "Date", type: "datetime" }),

    // SEO per item
    defineField({ name: "seoTitleLoc", title: "SEO Title (localized)", type: "localeSeoTitle" }),
    defineField({ name: "seoDescriptionLoc", title: "SEO Description (localized)", type: "localeSeoDescription" }),
    defineField({ name: "ogImage", title: "OG Image (optional)", type: "image", options: { hotspot: true } }),
    defineField({ name: "autoSyncSeo", title: "Auto-sync translations if not manually edited", type: "boolean", initialValue: true }),
  ],
  preview: {
    select: { title: "title", media: "thumb" },
  },
});
